/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Utils.AttributeListener;
import javax.swing.JLabel;

/**
 *
 * @author BlueMoon
 */
public class AttributesPanel extends javax.swing.JPanel {

    /**
     * Creates new form AttributesPanel
     */
    public AttributesPanel() {
        initComponents();
        
    }
    
    public void setListeners(Gui g){
        strScore.getDocument().addDocumentListener(new AttributeListener(g, strScore, "STR", strModifier, g.aCPanel1.acScore));
        dexScore.getDocument().addDocumentListener(new AttributeListener(g, dexScore, "DEX", dexModifier, g.aCPanel1.acScore));
        conScore.getDocument().addDocumentListener(new AttributeListener(g, conScore, "CON", conModifier, g.aCPanel1.acScore));
        intScore.getDocument().addDocumentListener(new AttributeListener(g, intScore, "INT", intModifier, g.aCPanel1.acScore));
        wisScore.getDocument().addDocumentListener(new AttributeListener(g, wisScore, "WIS", wisModifier, g.aCPanel1.acScore));
        chaScore.getDocument().addDocumentListener(new AttributeListener(g, chaScore, "CHA", chaModifier, g.aCPanel1.acScore));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        strScore = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        strModifier = new javax.swing.JLabel();
        dexModifier = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dexScore = new javax.swing.JTextField();
        conScore = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        conModifier = new javax.swing.JLabel();
        intModifier = new javax.swing.JLabel();
        wisModifier = new javax.swing.JLabel();
        chaModifier = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        intScore = new javax.swing.JTextField();
        wisScore = new javax.swing.JTextField();
        chaScore = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        strScore.setText("10");

        jLabel1.setText("STR");

        strModifier.setText("0");

        dexModifier.setText("0");

        jLabel2.setText("DEX");

        dexScore.setText("10");

        conScore.setText("10");

        jLabel3.setText("CON");

        conModifier.setText("0");

        intModifier.setText("0");

        wisModifier.setText("0");

        chaModifier.setText("0");

        jLabel6.setText("CHA");
        jLabel6.setToolTipText("");

        jLabel5.setText("WIS");

        jLabel4.setText("INT");

        intScore.setText("10");

        wisScore.setText("10");

        chaScore.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(strScore, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(dexScore, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conScore, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(intScore, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wisScore, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chaScore, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(strModifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chaModifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dexModifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(conModifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(intModifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wisModifier)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(strModifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dexScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dexModifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(conModifier))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(intModifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wisScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(wisModifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chaScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(chaModifier))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel chaModifier;
    public javax.swing.JTextField chaScore;
    public javax.swing.JLabel conModifier;
    public javax.swing.JTextField conScore;
    public javax.swing.JLabel dexModifier;
    public javax.swing.JTextField dexScore;
    public javax.swing.JLabel intModifier;
    public javax.swing.JTextField intScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel strModifier;
    public javax.swing.JTextField strScore;
    public javax.swing.JLabel wisModifier;
    public javax.swing.JTextField wisScore;
    // End of variables declaration//GEN-END:variables
}
